import React, { useState, useCallback, useEffect } from 'react'
import Navbar from './components/Navbar'
import Hero from './components/Hero'
import Upscaling from './components/Upscaling'
import VideoShowcase from './components/VideoShowcase'
import CharacterConsistency from './components/CharacterConsistency'
import Tools from './components/Tools'
import About from './components/About'
import Process from './components/Process'
import Contact from './components/Contact'
import Footer from './components/Footer'
import Lightbox from './components/Lightbox'
import './styles/index.css'
import './styles/components.css'

const reels = [
  {
    id: 'kitchen',
    video: '/kitchen.mp4',
    title: 'AI Kitchen Environment',
    desc: 'Hyper-realistic kitchen scene with photorealistic textures and lighting.',
    meta: ['4K', 'Runway ML'],
    category: 'cinematic',
  },
  {
    id: 'samurai',
    video: '/samurai.mp4',
    title: 'Samurai Duel',
    desc: 'Intense combat choreography through AI motion synthesis.',
    meta: ['4K', 'Pika Labs'],
    category: 'action',
  },
  {
    id: 'restaurant',
    video: '/restaurant.mp4',
    title: 'Restaurant Animation',
    desc: 'Stylized architectural walkthrough with dynamic AI motion.',
    meta: ['HD', 'Leonardo AI'],
    category: 'artistic',
  },
  {
    id: 'safari',
    video: '/safari.mp4',
    title: 'Safari Commercial',
    desc: 'Wildlife cinematography created with AI video synthesis.',
    meta: ['4K', 'Runway ML'],
    category: 'commercial',
  },
  {
    id: 'flux-art',
    video: '/flux-art.mp4',
    title: "Thinking They're Real — FLUX 3",
    desc: 'Surreal visuals challenging perception through advanced diffusion models.',
    meta: ['4K', 'FLUX 3'],
    category: 'artistic',
  },
  {
    id: 'game',
    video: '/game.mp4',
    title: 'AI Game Visuals',
    desc: 'Next-gen gaming aesthetics with AI scene synthesis.',
    meta: ['HD', 'Stable Video'],
    category: 'cinematic',
  },
  {
    id: 'rap',
    video: '/rap.mp4',
    title: 'AI Rap Video',
    desc: 'Music video visuals pulsing with rhythm, generated by AI.',
    meta: ['HD', 'Pika Labs'],
    category: 'commercial',
  },
]

function App() {
  const [lightbox, setLightbox] = useState({ open: false, video: '', title: '', desc: '' })

  const openLightbox = useCallback((video, title, desc) => {
    setLightbox({ open: true, video, title, desc })
    document.body.style.overflow = 'hidden'
  }, [])

  const closeLightbox = useCallback(() => {
    setLightbox(prev => ({ ...prev, open: false }))
    document.body.style.overflow = ''
  }, [])

  return (
    <>
      <Navbar />
      <Hero />
      <Upscaling />
      <VideoShowcase reels={reels} onOpen={openLightbox} />
      <CharacterConsistency />
      <Tools />
      <About />
      <Process />
      <Contact />
      <Footer />
      <Lightbox
        open={lightbox.open}
        video={lightbox.video}
        title={lightbox.title}
        desc={lightbox.desc}
        onClose={closeLightbox}
      />
    </>
  )
}

export default App
